cd /usr/share/fonts/truetype/noto/

sudo wget https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-hinted.zip
sudo wget https://noto-website-2.storage.googleapis.com/pkgs/NotoSerif-hinted.zip
sudo wget https://noto-website-2.storage.googleapis.com/pkgs/NotoSansDisplay-hinted.zip
sudo wget https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifDisplay-hinted.zip
sudo wget https://noto-website-2.storage.googleapis.com/pkgs/NotoMono-hinted.zip
sudo wget https://noto-website-2.storage.googleapis.com/pkgs/NotoColorEmoji-unhinted.zip
sudo wget https://noto-website-2.storage.googleapis.com/pkgs/NotoSansKannada-hinted.zip
sudo wget https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifKannada-hinted.zip

sudo unzip NotoSans-hinted.zip -o
sudo unzip NotoSerif-hinted.zip -o
sudo unzip NotoSansDisplay-hinted.zip -o
sudo unzip NotoSerifDisplay-hinted.zip -o
sudo unzip NotoMono-hinted.zip -o
sudo unzip NotoColorEmoji-unhinted.zip -o
sudo unzip NotoSansKannada-hinted.zip -o
sudo unzip NotoSerifKannada-hinted.zip -o

sudo rm -v NotoSans-hinted.zip
sudo rm -v NotoSerif-hinted.zip
sudo rm -v NotoSansDisplay-hinted.zip
sudo rm -v NotoSerifDisplay-hinted.zip
sudo rm -v NotoMono-hinted.zip
sudo rm -v NotoColorEmoji-unhinted.zip
sudo rm -v NotoSansKannada-hinted.zip
sudo rm -v NotoSerifKannada-hinted.zip

sudo chmod 644 NotoColorEmoji.ttf
sudo chmod 644 NotoMono-Regular.ttf
sudo chmod 644 NotoSans-Black.ttf
sudo chmod 644 NotoSans-BlackItalic.ttf
sudo chmod 644 NotoSans-Bold.ttf
sudo chmod 644 NotoSans-BoldItalic.ttf
sudo chmod 644 NotoSans-Condensed.ttf
sudo chmod 644 NotoSans-CondensedBlack.ttf
sudo chmod 644 NotoSans-CondensedBlackItalic.ttf
sudo chmod 644 NotoSans-CondensedBold.ttf
sudo chmod 644 NotoSans-CondensedBoldItalic.ttf
sudo chmod 644 NotoSans-CondensedExtraBold.ttf
sudo chmod 644 NotoSans-CondensedExtraBoldItalic.ttf
sudo chmod 644 NotoSans-CondensedExtraLight.ttf
sudo chmod 644 NotoSans-CondensedExtraLightItalic.ttf
sudo chmod 644 NotoSans-CondensedItalic.ttf
sudo chmod 644 NotoSans-CondensedLight.ttf
sudo chmod 644 NotoSans-CondensedLightItalic.ttf
sudo chmod 644 NotoSans-CondensedMedium.ttf
sudo chmod 644 NotoSans-CondensedMediumItalic.ttf
sudo chmod 644 NotoSans-CondensedSemiBold.ttf
sudo chmod 644 NotoSans-CondensedSemiBoldItalic.ttf
sudo chmod 644 NotoSans-CondensedThin.ttf
sudo chmod 644 NotoSans-CondensedThinItalic.ttf
sudo chmod 644 NotoSansDisplay-Black.ttf
sudo chmod 644 NotoSansDisplay-BlackItalic.ttf
sudo chmod 644 NotoSansDisplay-Bold.ttf
sudo chmod 644 NotoSansDisplay-BoldItalic.ttf
sudo chmod 644 NotoSansDisplay-Condensed.ttf
sudo chmod 644 NotoSansDisplay-CondensedBlack.ttf
sudo chmod 644 NotoSansDisplay-CondensedBlackItalic.ttf
sudo chmod 644 NotoSansDisplay-CondensedBold.ttf
sudo chmod 644 NotoSansDisplay-CondensedBoldItalic.ttf
sudo chmod 644 NotoSansDisplay-CondensedExtraBold.ttf
sudo chmod 644 NotoSansDisplay-CondensedExtraBoldItalic.ttf
sudo chmod 644 NotoSansDisplay-CondensedExtraLight.ttf
sudo chmod 644 NotoSansDisplay-CondensedExtraLightItalic.ttf
sudo chmod 644 NotoSansDisplay-CondensedItalic.ttf
sudo chmod 644 NotoSansDisplay-CondensedLight.ttf
sudo chmod 644 NotoSansDisplay-CondensedLightItalic.ttf
sudo chmod 644 NotoSansDisplay-CondensedMedium.ttf
sudo chmod 644 NotoSansDisplay-CondensedMediumItalic.ttf
sudo chmod 644 NotoSansDisplay-CondensedSemiBold.ttf
sudo chmod 644 NotoSansDisplay-CondensedSemiBoldItalic.ttf
sudo chmod 644 NotoSansDisplay-CondensedThin.ttf
sudo chmod 644 NotoSansDisplay-CondensedThinItalic.ttf
sudo chmod 644 NotoSansDisplay-ExtraBold.ttf
sudo chmod 644 NotoSansDisplay-ExtraBoldItalic.ttf
sudo chmod 644 NotoSansDisplay-ExtraCondensed.ttf
sudo chmod 644 NotoSansDisplay-ExtraCondensedBlack.ttf
sudo chmod 644 NotoSansDisplay-ExtraCondensedBlackItalic.ttf
sudo chmod 644 NotoSansDisplay-ExtraCondensedBold.ttf
sudo chmod 644 NotoSansDisplay-ExtraCondensedBoldItalic.ttf
sudo chmod 644 NotoSansDisplay-ExtraCondensedExtraBold.ttf
sudo chmod 644 NotoSansDisplay-ExtraCondensedExtraBoldItalic.ttf
sudo chmod 644 NotoSansDisplay-ExtraCondensedExtraLight.ttf
sudo chmod 644 NotoSansDisplay-ExtraCondensedExtraLightItalic.ttf
sudo chmod 644 NotoSansDisplay-ExtraCondensedItalic.ttf
sudo chmod 644 NotoSansDisplay-ExtraCondensedLight.ttf
sudo chmod 644 NotoSansDisplay-ExtraCondensedLightItalic.ttf
sudo chmod 644 NotoSansDisplay-ExtraCondensedMedium.ttf
sudo chmod 644 NotoSansDisplay-ExtraCondensedMediumItalic.ttf
sudo chmod 644 NotoSansDisplay-ExtraCondensedSemiBold.ttf
sudo chmod 644 NotoSansDisplay-ExtraCondensedSemiBoldItalic.ttf
sudo chmod 644 NotoSansDisplay-ExtraCondensedThin.ttf
sudo chmod 644 NotoSansDisplay-ExtraCondensedThinItalic.ttf
sudo chmod 644 NotoSansDisplay-ExtraLight.ttf
sudo chmod 644 NotoSansDisplay-ExtraLightItalic.ttf
sudo chmod 644 NotoSansDisplay-Italic.ttf
sudo chmod 644 NotoSansDisplay-Light.ttf
sudo chmod 644 NotoSansDisplay-LightItalic.ttf
sudo chmod 644 NotoSansDisplay-Medium.ttf
sudo chmod 644 NotoSansDisplay-MediumItalic.ttf
sudo chmod 644 NotoSansDisplay-Regular.ttf
sudo chmod 644 NotoSansDisplay-SemiBold.ttf
sudo chmod 644 NotoSansDisplay-SemiBoldItalic.ttf
sudo chmod 644 NotoSansDisplay-SemiCondensed.ttf
sudo chmod 644 NotoSansDisplay-SemiCondensedBlack.ttf
sudo chmod 644 NotoSansDisplay-SemiCondensedBlackItalic.ttf
sudo chmod 644 NotoSansDisplay-SemiCondensedBold.ttf
sudo chmod 644 NotoSansDisplay-SemiCondensedBoldItalic.ttf
sudo chmod 644 NotoSansDisplay-SemiCondensedExtraBold.ttf
sudo chmod 644 NotoSansDisplay-SemiCondensedExtraBoldItalic.ttf
sudo chmod 644 NotoSansDisplay-SemiCondensedExtraLight.ttf
sudo chmod 644 NotoSansDisplay-SemiCondensedExtraLightItalic.ttf
sudo chmod 644 NotoSansDisplay-SemiCondensedItalic.ttf
sudo chmod 644 NotoSansDisplay-SemiCondensedLight.ttf
sudo chmod 644 NotoSansDisplay-SemiCondensedLightItalic.ttf
sudo chmod 644 NotoSansDisplay-SemiCondensedMedium.ttf
sudo chmod 644 NotoSansDisplay-SemiCondensedMediumItalic.ttf
sudo chmod 644 NotoSansDisplay-SemiCondensedSemiBold.ttf
sudo chmod 644 NotoSansDisplay-SemiCondensedSemiBoldItalic.ttf
sudo chmod 644 NotoSansDisplay-SemiCondensedThin.ttf
sudo chmod 644 NotoSansDisplay-SemiCondensedThinItalic.ttf
sudo chmod 644 NotoSansDisplay-Thin.ttf
sudo chmod 644 NotoSansDisplay-ThinItalic.ttf
sudo chmod 644 NotoSans-ExtraBold.ttf
sudo chmod 644 NotoSans-ExtraBoldItalic.ttf
sudo chmod 644 NotoSans-ExtraCondensed.ttf
sudo chmod 644 NotoSans-ExtraCondensedBlack.ttf
sudo chmod 644 NotoSans-ExtraCondensedBlackItalic.ttf
sudo chmod 644 NotoSans-ExtraCondensedBold.ttf
sudo chmod 644 NotoSans-ExtraCondensedBoldItalic.ttf
sudo chmod 644 NotoSans-ExtraCondensedExtraBold.ttf
sudo chmod 644 NotoSans-ExtraCondensedExtraBoldItalic.ttf
sudo chmod 644 NotoSans-ExtraCondensedExtraLight.ttf
sudo chmod 644 NotoSans-ExtraCondensedExtraLightItalic.ttf
sudo chmod 644 NotoSans-ExtraCondensedItalic.ttf
sudo chmod 644 NotoSans-ExtraCondensedLight.ttf
sudo chmod 644 NotoSans-ExtraCondensedLightItalic.ttf
sudo chmod 644 NotoSans-ExtraCondensedMedium.ttf
sudo chmod 644 NotoSans-ExtraCondensedMediumItalic.ttf
sudo chmod 644 NotoSans-ExtraCondensedSemiBold.ttf
sudo chmod 644 NotoSans-ExtraCondensedSemiBoldItalic.ttf
sudo chmod 644 NotoSans-ExtraCondensedThin.ttf
sudo chmod 644 NotoSans-ExtraCondensedThinItalic.ttf
sudo chmod 644 NotoSans-ExtraLight.ttf
sudo chmod 644 NotoSans-ExtraLightItalic.ttf
sudo chmod 644 NotoSans-Italic.ttf
sudo chmod 644 NotoSansKannada-Bold.ttf
sudo chmod 644 NotoSansKannada-Regular.ttf
sudo chmod 644 NotoSansKannadaUI-Bold.ttf
sudo chmod 644 NotoSansKannadaUI-Regular.ttf
sudo chmod 644 NotoSans-Light.ttf
sudo chmod 644 NotoSans-LightItalic.ttf
sudo chmod 644 NotoSans-Medium.ttf
sudo chmod 644 NotoSans-MediumItalic.ttf
sudo chmod 644 NotoSans-Regular.ttf
sudo chmod 644 NotoSans-SemiBold.ttf
sudo chmod 644 NotoSans-SemiBoldItalic.ttf
sudo chmod 644 NotoSans-SemiCondensed.ttf
sudo chmod 644 NotoSans-SemiCondensedBlack.ttf
sudo chmod 644 NotoSans-SemiCondensedBlackItalic.ttf
sudo chmod 644 NotoSans-SemiCondensedBold.ttf
sudo chmod 644 NotoSans-SemiCondensedBoldItalic.ttf
sudo chmod 644 NotoSans-SemiCondensedExtraBold.ttf
sudo chmod 644 NotoSans-SemiCondensedExtraBoldItalic.ttf
sudo chmod 644 NotoSans-SemiCondensedExtraLight.ttf
sudo chmod 644 NotoSans-SemiCondensedExtraLightItalic.ttf
sudo chmod 644 NotoSans-SemiCondensedItalic.ttf
sudo chmod 644 NotoSans-SemiCondensedLight.ttf
sudo chmod 644 NotoSans-SemiCondensedLightItalic.ttf
sudo chmod 644 NotoSans-SemiCondensedMedium.ttf
sudo chmod 644 NotoSans-SemiCondensedMediumItalic.ttf
sudo chmod 644 NotoSans-SemiCondensedSemiBold.ttf
sudo chmod 644 NotoSans-SemiCondensedSemiBoldItalic.ttf
sudo chmod 644 NotoSans-SemiCondensedThin.ttf
sudo chmod 644 NotoSans-SemiCondensedThinItalic.ttf
sudo chmod 644 NotoSans-Thin.ttf
sudo chmod 644 NotoSans-ThinItalic.ttf
sudo chmod 644 NotoSerif-Black.ttf
sudo chmod 644 NotoSerif-BlackItalic.ttf
sudo chmod 644 NotoSerif-Bold.ttf
sudo chmod 644 NotoSerif-BoldItalic.ttf
sudo chmod 644 NotoSerif-Condensed.ttf
sudo chmod 644 NotoSerif-CondensedBlack.ttf
sudo chmod 644 NotoSerif-CondensedBlackItalic.ttf
sudo chmod 644 NotoSerif-CondensedBold.ttf
sudo chmod 644 NotoSerif-CondensedBoldItalic.ttf
sudo chmod 644 NotoSerif-CondensedExtraBold.ttf
sudo chmod 644 NotoSerif-CondensedExtraBoldItalic.ttf
sudo chmod 644 NotoSerif-CondensedExtraLight.ttf
sudo chmod 644 NotoSerif-CondensedExtraLightItalic.ttf
sudo chmod 644 NotoSerif-CondensedItalic.ttf
sudo chmod 644 NotoSerif-CondensedLight.ttf
sudo chmod 644 NotoSerif-CondensedLightItalic.ttf
sudo chmod 644 NotoSerif-CondensedMedium.ttf
sudo chmod 644 NotoSerif-CondensedMediumItalic.ttf
sudo chmod 644 NotoSerif-CondensedSemiBold.ttf
sudo chmod 644 NotoSerif-CondensedSemiBoldItalic.ttf
sudo chmod 644 NotoSerif-CondensedThin.ttf
sudo chmod 644 NotoSerif-CondensedThinItalic.ttf
sudo chmod 644 NotoSerifDisplay-Black.ttf
sudo chmod 644 NotoSerifDisplay-BlackItalic.ttf
sudo chmod 644 NotoSerifDisplay-Bold.ttf
sudo chmod 644 NotoSerifDisplay-BoldItalic.ttf
sudo chmod 644 NotoSerifDisplay-Condensed.ttf
sudo chmod 644 NotoSerifDisplay-CondensedBlack.ttf
sudo chmod 644 NotoSerifDisplay-CondensedBlackItalic.ttf
sudo chmod 644 NotoSerifDisplay-CondensedBold.ttf
sudo chmod 644 NotoSerifDisplay-CondensedBoldItalic.ttf
sudo chmod 644 NotoSerifDisplay-CondensedExtraBold.ttf
sudo chmod 644 NotoSerifDisplay-CondensedExtraBoldItalic.ttf
sudo chmod 644 NotoSerifDisplay-CondensedExtraLight.ttf
sudo chmod 644 NotoSerifDisplay-CondensedExtraLightItalic.ttf
sudo chmod 644 NotoSerifDisplay-CondensedItalic.ttf
sudo chmod 644 NotoSerifDisplay-CondensedLight.ttf
sudo chmod 644 NotoSerifDisplay-CondensedLightItalic.ttf
sudo chmod 644 NotoSerifDisplay-CondensedMedium.ttf
sudo chmod 644 NotoSerifDisplay-CondensedMediumItalic.ttf
sudo chmod 644 NotoSerifDisplay-CondensedSemiBold.ttf
sudo chmod 644 NotoSerifDisplay-CondensedSemiBoldItalic.ttf
sudo chmod 644 NotoSerifDisplay-CondensedThin.ttf
sudo chmod 644 NotoSerifDisplay-CondensedThinItalic.ttf
sudo chmod 644 NotoSerifDisplay-ExtraBold.ttf
sudo chmod 644 NotoSerifDisplay-ExtraBoldItalic.ttf
sudo chmod 644 NotoSerifDisplay-ExtraCondensed.ttf
sudo chmod 644 NotoSerifDisplay-ExtraCondensedBlack.ttf
sudo chmod 644 NotoSerifDisplay-ExtraCondensedBlackItalic.ttf
sudo chmod 644 NotoSerifDisplay-ExtraCondensedBold.ttf
sudo chmod 644 NotoSerifDisplay-ExtraCondensedBoldItalic.ttf
sudo chmod 644 NotoSerifDisplay-ExtraCondensedExtraBold.ttf
sudo chmod 644 NotoSerifDisplay-ExtraCondensedExtraBoldItalic.ttf
sudo chmod 644 NotoSerifDisplay-ExtraCondensedExtraLight.ttf
sudo chmod 644 NotoSerifDisplay-ExtraCondensedExtraLightItalic.ttf
sudo chmod 644 NotoSerifDisplay-ExtraCondensedItalic.ttf
sudo chmod 644 NotoSerifDisplay-ExtraCondensedLight.ttf
sudo chmod 644 NotoSerifDisplay-ExtraCondensedLightItalic.ttf
sudo chmod 644 NotoSerifDisplay-ExtraCondensedMedium.ttf
sudo chmod 644 NotoSerifDisplay-ExtraCondensedMediumItalic.ttf
sudo chmod 644 NotoSerifDisplay-ExtraCondensedSemiBold.ttf
sudo chmod 644 NotoSerifDisplay-ExtraCondensedSemiBoldItalic.ttf
sudo chmod 644 NotoSerifDisplay-ExtraCondensedThin.ttf
sudo chmod 644 NotoSerifDisplay-ExtraCondensedThinItalic.ttf
sudo chmod 644 NotoSerifDisplay-ExtraLight.ttf
sudo chmod 644 NotoSerifDisplay-ExtraLightItalic.ttf
sudo chmod 644 NotoSerifDisplay-Italic.ttf
sudo chmod 644 NotoSerifDisplay-Light.ttf
sudo chmod 644 NotoSerifDisplay-LightItalic.ttf
sudo chmod 644 NotoSerifDisplay-Medium.ttf
sudo chmod 644 NotoSerifDisplay-MediumItalic.ttf
sudo chmod 644 NotoSerifDisplay-Regular.ttf
sudo chmod 644 NotoSerifDisplay-SemiBold.ttf
sudo chmod 644 NotoSerifDisplay-SemiBoldItalic.ttf
sudo chmod 644 NotoSerifDisplay-SemiCondensed.ttf
sudo chmod 644 NotoSerifDisplay-SemiCondensedBlack.ttf
sudo chmod 644 NotoSerifDisplay-SemiCondensedBlackItalic.ttf
sudo chmod 644 NotoSerifDisplay-SemiCondensedBold.ttf
sudo chmod 644 NotoSerifDisplay-SemiCondensedBoldItalic.ttf
sudo chmod 644 NotoSerifDisplay-SemiCondensedExtraBold.ttf
sudo chmod 644 NotoSerifDisplay-SemiCondensedExtraBoldItalic.ttf
sudo chmod 644 NotoSerifDisplay-SemiCondensedExtraLight.ttf
sudo chmod 644 NotoSerifDisplay-SemiCondensedExtraLightItalic.ttf
sudo chmod 644 NotoSerifDisplay-SemiCondensedItalic.ttf
sudo chmod 644 NotoSerifDisplay-SemiCondensedLight.ttf
sudo chmod 644 NotoSerifDisplay-SemiCondensedLightItalic.ttf
sudo chmod 644 NotoSerifDisplay-SemiCondensedMedium.ttf
sudo chmod 644 NotoSerifDisplay-SemiCondensedMediumItalic.ttf
sudo chmod 644 NotoSerifDisplay-SemiCondensedSemiBold.ttf
sudo chmod 644 NotoSerifDisplay-SemiCondensedSemiBoldItalic.ttf
sudo chmod 644 NotoSerifDisplay-SemiCondensedThin.ttf
sudo chmod 644 NotoSerifDisplay-SemiCondensedThinItalic.ttf
sudo chmod 644 NotoSerifDisplay-Thin.ttf
sudo chmod 644 NotoSerifDisplay-ThinItalic.ttf
sudo chmod 644 NotoSerif-ExtraBold.ttf
sudo chmod 644 NotoSerif-ExtraBoldItalic.ttf
sudo chmod 644 NotoSerif-ExtraCondensed.ttf
sudo chmod 644 NotoSerif-ExtraCondensedBlack.ttf
sudo chmod 644 NotoSerif-ExtraCondensedBlackItalic.ttf
sudo chmod 644 NotoSerif-ExtraCondensedBold.ttf
sudo chmod 644 NotoSerif-ExtraCondensedBoldItalic.ttf
sudo chmod 644 NotoSerif-ExtraCondensedExtraBold.ttf
sudo chmod 644 NotoSerif-ExtraCondensedExtraBoldItalic.ttf
sudo chmod 644 NotoSerif-ExtraCondensedExtraLight.ttf
sudo chmod 644 NotoSerif-ExtraCondensedExtraLightItalic.ttf
sudo chmod 644 NotoSerif-ExtraCondensedItalic.ttf
sudo chmod 644 NotoSerif-ExtraCondensedLight.ttf
sudo chmod 644 NotoSerif-ExtraCondensedLightItalic.ttf
sudo chmod 644 NotoSerif-ExtraCondensedMedium.ttf
sudo chmod 644 NotoSerif-ExtraCondensedMediumItalic.ttf
sudo chmod 644 NotoSerif-ExtraCondensedSemiBold.ttf
sudo chmod 644 NotoSerif-ExtraCondensedSemiBoldItalic.ttf
sudo chmod 644 NotoSerif-ExtraCondensedThin.ttf
sudo chmod 644 NotoSerif-ExtraCondensedThinItalic.ttf
sudo chmod 644 NotoSerif-ExtraLight.ttf
sudo chmod 644 NotoSerif-ExtraLightItalic.ttf
sudo chmod 644 NotoSerif-Italic.ttf
sudo chmod 644 NotoSerifKannada-Bold.ttf
sudo chmod 644 NotoSerifKannada-Regular.ttf
sudo chmod 644 NotoSerif-Light.ttf
sudo chmod 644 NotoSerif-LightItalic.ttf
sudo chmod 644 NotoSerif-Medium.ttf
sudo chmod 644 NotoSerif-MediumItalic.ttf
sudo chmod 644 NotoSerif-Regular.ttf
sudo chmod 644 NotoSerif-SemiBold.ttf
sudo chmod 644 NotoSerif-SemiBoldItalic.ttf
sudo chmod 644 NotoSerif-SemiCondensed.ttf
sudo chmod 644 NotoSerif-SemiCondensedBlack.ttf
sudo chmod 644 NotoSerif-SemiCondensedBlackItalic.ttf
sudo chmod 644 NotoSerif-SemiCondensedBold.ttf
sudo chmod 644 NotoSerif-SemiCondensedBoldItalic.ttf
sudo chmod 644 NotoSerif-SemiCondensedExtraBold.ttf
sudo chmod 644 NotoSerif-SemiCondensedExtraBoldItalic.ttf
sudo chmod 644 NotoSerif-SemiCondensedExtraLight.ttf
sudo chmod 644 NotoSerif-SemiCondensedExtraLightItalic.ttf
sudo chmod 644 NotoSerif-SemiCondensedItalic.ttf
sudo chmod 644 NotoSerif-SemiCondensedLight.ttf
sudo chmod 644 NotoSerif-SemiCondensedLightItalic.ttf
sudo chmod 644 NotoSerif-SemiCondensedMedium.ttf
sudo chmod 644 NotoSerif-SemiCondensedMediumItalic.ttf
sudo chmod 644 NotoSerif-SemiCondensedSemiBold.ttf
sudo chmod 644 NotoSerif-SemiCondensedSemiBoldItalic.ttf
sudo chmod 644 NotoSerif-SemiCondensedThin.ttf
sudo chmod 644 NotoSerif-SemiCondensedThinItalic.ttf
sudo chmod 644 NotoSerif-Thin.ttf
sudo chmod 644 NotoSerif-ThinItalic.ttf

fc-cache -f -v

sudo reboot